[build]
  base = "nutricionista-web"
  command = "npm run build"
  publish = "nutricionista-web/.next"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
